/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import tallercontenedores.contenedor_area;
import tallercontenedores.contenedor_doctor;
import static GUI.area.are;
import static GUI.area.are2;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author SENA
 */
public class doctor extends javax.swing.JFrame {
     public static java.util.ArrayList doc = new java.util.ArrayList<>();
    public static contenedor_doctor doc2 = null;
    public static String opcion = null;
    private DefaultTableModel model; // ATRIBUTO DE CLASE
    

    /**
     * Creates new form doctor
     */
    public doctor() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cedula = new javax.swing.JTextField();
        nombre = new javax.swing.JTextField();
        telefono = new javax.swing.JTextField();
        tipo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        area_d = new javax.swing.JComboBox<>();
        agregar = new javax.swing.JButton();
        modificar = new javax.swing.JButton();
        buscar = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        enviar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla_doctor = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();

        jTextField2.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(553, 435));
        setMinimumSize(new java.awt.Dimension(435, 553));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("DOCTOR");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(170, 0, 61, 17);

        jLabel2.setText("Cedula:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(123, 40, 50, 20);

        jLabel3.setText("Nombre:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(119, 70, 60, 14);

        jLabel4.setText("Telefono:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(123, 100, 60, 14);

        jLabel5.setText("Tipo:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(138, 130, 40, 14);
        getContentPane().add(cedula);
        cedula.setBounds(190, 38, 77, 20);
        getContentPane().add(nombre);
        nombre.setBounds(190, 68, 77, 20);
        getContentPane().add(telefono);
        telefono.setBounds(190, 98, 80, 20);

        tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "General", "Especialista" }));
        tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoActionPerformed(evt);
            }
        });
        getContentPane().add(tipo);
        tipo.setBounds(190, 130, 80, 20);

        jLabel6.setText("Area:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(140, 160, 40, 14);

        area_d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area_dActionPerformed(evt);
            }
        });
        getContentPane().add(area_d);
        area_d.setBounds(190, 160, 80, 20);

        agregar.setText("agregar");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });
        getContentPane().add(agregar);
        agregar.setBounds(10, 190, 71, 23);

        modificar.setText("modificar");
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });
        getContentPane().add(modificar);
        modificar.setBounds(100, 190, 75, 23);

        buscar.setText("buscar");
        getContentPane().add(buscar);
        buscar.setBounds(210, 190, 65, 23);

        eliminar.setText("eliminar");
        getContentPane().add(eliminar);
        eliminar.setBounds(320, 190, 69, 23);

        enviar.setText("mostrar");
        enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarActionPerformed(evt);
            }
        });
        getContentPane().add(enviar);
        enviar.setBounds(180, 240, 69, 23);

        tabla_doctor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Cedula", "Nombre", "Telefono", "Tipo", "Area"
            }
        ));
        jScrollPane2.setViewportView(tabla_doctor);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 270, 410, 130);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/fondodoctor.jpg"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(-10, 0, 460, 417);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void area_dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area_dActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_area_dActionPerformed

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        // TODO add your handling code here:
    String opcion1=(String)tipo.getSelectedItem(); 
    if(opcion1.equals("General")){
    String nom = nombre.getText().trim();
    int ced = Integer.parseInt(cedula.getText().trim());
    int tel = Integer.parseInt(telefono.getText().trim());
    String tipod = (String) tipo.getSelectedItem();
    String espe = "";
    contenedor_doctor d1 = new contenedor_doctor(ced, nom, tel, tipod, espe);
    doc.add(d1);
    }
        
    String opcion2=(String)tipo.getSelectedItem(); 
    if(opcion2.equals("Especialista")){
    String nom = nombre.getText().trim();
    int ced = Integer.parseInt(cedula.getText().trim());
    int tel = Integer.parseInt(telefono.getText().trim());
    String tipod = (String) tipo.getSelectedItem();
    String espe = (String) area_d.getSelectedItem();
    contenedor_doctor d1 = new contenedor_doctor(ced, nom, tel, tipod, espe);
    doc.add(d1);
    }
    cedula.setText(null);
    nombre.setText(null);
    telefono.setText(null);
    tipo.setSelectedItem("Seleccione");
        
    }//GEN-LAST:event_agregarActionPerformed

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
        // TODO add your handling code here:
        doc2.setNombre(nombre.getText().trim());
        doc2.setTelefono(Integer.parseInt(telefono.getText().trim()));        
    }//GEN-LAST:event_modificarActionPerformed

    private void enviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarActionPerformed
        // TODO add your handling code here:
         //datos.setText(null);
         String data[][] = {};
         String col[] = {"Cedula","Nombre","Telefono","Tipo","Area"};
         model = new DefaultTableModel(data,col);
         tabla_doctor.setModel(model);
         int con=0;
        for(int i =0; i<doc.size(); i++)
        {
         contenedor_doctor d = (contenedor_doctor)doc.get(i);
         //datos.setText( datos.getText() + d.getCedeula()+ "\t" + d.getNombre() + "\t" + d.getTelefono() + "\t" + d.getEspecialista() + "\n" + "  " + "\n");
         model.insertRow(con,new Object[]{}); //INSERTA FILA EN TIEMPO DE EJECUCION
         model.setValueAt(d.getCedeula(), con, 0);  // ACTUALIZA LA CELDA CON EL VALOR DE CAMPO OBTENIDO
         model.setValueAt(d.getNombre(), con, 1);
         model.setValueAt(d.getTelefono(), con, 2);
         model.setValueAt(d.getGeneral(), con, 3);
         model.setValueAt(d.getEspecialista(), con, 4);
         con++;
    }//GEN-LAST:event_enviarActionPerformed
    }
    private void tipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoActionPerformed
        // TODO add your handling code here:
        contenedor_area are2= null;
        String op=(String)tipo.getSelectedItem();
        if(op.equals("Especialista"))
        {
            area_d.removeAllItems();
        for(int i=0; i<area.are.size();i++)
        {   are2=(contenedor_area)are.get(i);
            area_d.addItem(are2.getNombreA());
            }
                }
        else{
            area_d.removeAllItems();
        }
        //opcion = (String) tipo.getSelectedItem();
    }//GEN-LAST:event_tipoActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new doctor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregar;
    private javax.swing.JComboBox<String> area_d;
    private javax.swing.JButton buscar;
    private javax.swing.JTextField cedula;
    private javax.swing.JButton eliminar;
    private javax.swing.JButton enviar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton modificar;
    private javax.swing.JTextField nombre;
    private javax.swing.JTable tabla_doctor;
    private javax.swing.JTextField telefono;
    private javax.swing.JComboBox<String> tipo;
    // End of variables declaration//GEN-END:variables
}
