/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import tallercontenedores.contenedor_paciente;
import tallercontenedores.Archivo;

/**
 *
 * @author SENA
 */
public class paciente extends javax.swing.JFrame {
    public static java.util.ArrayList pac = new java.util.ArrayList<>();
    public static contenedor_paciente pac2 = null;
    private DefaultTableModel model;

    /**
     * Creates new form paciente
     */
    public paciente() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cedula = new javax.swing.JTextField();
        nombre = new javax.swing.JTextField();
        edad = new javax.swing.JTextField();
        telefono = new javax.swing.JTextField();
        agregar = new javax.swing.JButton();
        modificar = new javax.swing.JButton();
        buscar = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        enviar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla_paciente = new javax.swing.JTable();
        exportar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(485, 450));
        setPreferredSize(new java.awt.Dimension(472, 378));
        getContentPane().setLayout(null);

        jLabel1.setText("Cedula:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(121, 56, 40, 16);

        jLabel2.setText("Nombre:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(121, 94, 47, 16);

        jLabel3.setText("Edad:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(121, 132, 29, 16);

        jLabel4.setText("Telefono:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(121, 170, 49, 16);

        cedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cedulaActionPerformed(evt);
            }
        });
        getContentPane().add(cedula);
        cedula.setBounds(228, 53, 68, 22);
        getContentPane().add(nombre);
        nombre.setBounds(228, 91, 68, 22);
        getContentPane().add(edad);
        edad.setBounds(228, 129, 68, 22);
        getContentPane().add(telefono);
        telefono.setBounds(228, 167, 68, 22);

        agregar.setText("agregar");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });
        getContentPane().add(agregar);
        agregar.setBounds(31, 193, 73, 25);

        modificar.setText("modificar");
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });
        getContentPane().add(modificar);
        modificar.setBounds(121, 193, 83, 25);

        buscar.setText("buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });
        getContentPane().add(buscar);
        buscar.setBounds(228, 193, 67, 25);

        eliminar.setText("eliminar");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });
        getContentPane().add(eliminar);
        eliminar.setBounds(320, 193, 75, 25);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("PACIENTE");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(164, 18, 74, 17);

        enviar.setText("mostrar");
        enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarActionPerformed(evt);
            }
        });
        getContentPane().add(enviar);
        enviar.setBounds(75, 234, 73, 25);

        tabla_paciente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Cedula", "Nombre", "Edad", "Telefono"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabla_paciente);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 275, 452, 96);

        exportar.setText("Exportar");
        exportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportarActionPerformed(evt);
            }
        });
        getContentPane().add(exportar);
        exportar.setBounds(258, 234, 77, 25);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/paciente.jpg"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 470, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        // TODO add your handling code here:
        int ced = Integer.parseInt(cedula.getText().trim());
        String nom = nombre.getText().trim();
        int ed = Integer.parseInt(edad.getText().trim());
        long tel = Long.parseLong(telefono.getText().trim());
     
        contenedor_paciente pac1 = new contenedor_paciente(ced, nom, ed, tel);
     
        pac.add(pac1);
     
        cedula.setText(null);
        nombre.setText(null);
        edad.setText(null);
        telefono.setText(null);
    }//GEN-LAST:event_agregarActionPerformed

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
        // TODO add your handling code here:
        pac2.setNombre(nombre.getText().trim());
        pac2.setEdad(Integer.parseInt(edad.getText().trim()));
        pac2.setTelefono(Integer.parseInt(telefono.getText().trim()));
    }//GEN-LAST:event_modificarActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        // TODO add your handling code here:
        int ced = Integer.parseInt(cedula.getText().trim());
        
        boolean buscar = false;
        contenedor_paciente p = null;
     
        for(int i =0; i<pac.size(); i++)
        {
         pac2 = (contenedor_paciente)pac.get(i);

         if(ced==pac2.getCedula())
         {
           buscar = true;
           break;
         }      
        }

        if(buscar)
        {
          nombre.setText(pac2.getNombre());
          edad.setText(String.valueOf(pac2.getEdad()));
          telefono.setText(String.valueOf(pac2.getTelefono()));
        }else{
            JOptionPane.showMessageDialog(null,"No existen datos!","ERROR",JOptionPane.ERROR_MESSAGE);
        }
     
    }//GEN-LAST:event_buscarActionPerformed

    private void enviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarActionPerformed
        // TODO add your handling code here:
        //datos.setText(null);
        String data[][]={};
        String col[] = {"CEDULA", "NOMBRE","EDAD","TELEFONO"};
        model = new DefaultTableModel(data,col);
         tabla_paciente.setModel(model);
         int con=0;
     
        for(int i =0; i<pac.size(); i++)
        {
         contenedor_paciente p = (contenedor_paciente)pac.get(i);
         //datosA.setText( datosA.getText() + a.getNombreA() + "\t" + a.getId() + "\n" );
         model.insertRow(con,new Object[]{}); //INSERTA FILA EN TIEMPO DE EJECUCION
         model.setValueAt(p.getCedula(), con, 0);  // ACTUALIZA LA CELDA CON EL VALOR DE CAMPO OBTENIDO
         model.setValueAt(p.getNombre(), con, 1);  // ACTUALIZA LA CELDA CON EL VALOR DE CAMPO OBTENIDO
         model.setValueAt(p.getEdad(), con, 2);  // ACTUALIZA LA CELDA CON EL VALOR DE CAMPO OBTENIDO
         model.setValueAt(p.getTelefono(), con, 3);  // ACTUALIZA LA CELDA CON EL VALOR DE CAMPO OBTENIDO
         
         //nombre" + "\t" + "Edad " + "\t" + "Telefono" + "\n" + p.getCedula() + "\t" + p.getNombre() + "\t" + p.getEdad() + "\t" + p.getTelefono() + "\n" + "  " + "\n");
        
        }
    }//GEN-LAST:event_enviarActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        // TODO add your handling code here:
        pac.remove(pac2);
       nombre.setText(""); cedula.setText(""); nombre.setText(""); edad.setText(""); telefono.setText("");
    }//GEN-LAST:event_eliminarActionPerformed

    private void cedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cedulaActionPerformed

    private void exportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportarActionPerformed
        // TODO add your handling code here:
        String cad="Cedula \t Nombre \t Edad \t Telefono \n";
        
        for(int i =0; i<pac.size(); i++){
        contenedor_paciente p = (contenedor_paciente)pac.get(i);
        cad+= p.getCedula() + "\t" + p.getNombre() + "\t" + p.getEdad() + "\t" + p.getTelefono() + "\n";
    
     }
     
        Archivo.grabar("Pacientes.xls", cad);
    }//GEN-LAST:event_exportarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new paciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregar;
    private javax.swing.JButton buscar;
    private javax.swing.JTextField cedula;
    private javax.swing.JTextField edad;
    private javax.swing.JButton eliminar;
    private javax.swing.JButton enviar;
    private javax.swing.JButton exportar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton modificar;
    private javax.swing.JTextField nombre;
    private javax.swing.JTable tabla_paciente;
    private javax.swing.JTextField telefono;
    // End of variables declaration//GEN-END:variables
}
