/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import static GUI.area.are;
import static GUI.doctor.doc;
import javax.swing.JOptionPane;
import tallercontenedores.contenedor_salida;
import tallercontenedores.contenedor_ingreso;
import static GUI.ingreso.ingreso;
import static GUI.ingreso.ingreso2;
import static GUI.paciente.pac;
import static GUI.paciente.pac2;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import tallercontenedores.Conexion;
import tallercontenedores.contenedor_area;
import tallercontenedores.contenedor_doctor;
import tallercontenedores.contenedor_paciente;



/**
 *
 * @author SENA
 */
public class salida extends javax.swing.JFrame {
    public static java.util.ArrayList salida = new java.util.ArrayList();
    public static contenedor_salida salida2 = null;
    
    public static String patron = "dd/MMM/yyyy";
    public static String sfecha;
    public static DateFormat formato1;
    

    /**
     * Creates new form salida
     */
    public salida() {
        try {
            initComponents();
            
            Conexion con = new Conexion();
            con.ConexionPostgres();
            
            String query = "SELECT * FROM doctor ORDER BY especialidad_doctor";

            ResultSet rs = con.consultar(query);

            while (rs.next()) {
                nombre_doctor.addItem(rs.getInt("especialidad_doctor") + "-" + rs.getString("nombre_doctor"));
            }

            nombre_doctor.setEnabled(true);
            con.cerrar();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(salida.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(salida.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(salida.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(salida.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cedula_paciente = new javax.swing.JTextField();
        nombre_paciente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        fecha_i = new com.toedter.calendar.JDateChooser();
        modificar = new javax.swing.JButton();
        agregar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        fecha_salida = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        total = new javax.swing.JTextField();
        buscar = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        enviar = new javax.swing.JButton();
        exportar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        nombre_doctor = new javax.swing.JComboBox<>();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 600));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel2.setText("SALIDA DEL PACIENTE");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(273, 11, 139, 18);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("cedula del paciente:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 70, 120, 14);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Nombre del paciente:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(310, 70, 119, 14);
        getContentPane().add(cedula_paciente);
        cedula_paciente.setBounds(138, 70, 150, 20);

        nombre_paciente.setEditable(false);
        nombre_paciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombre_pacienteActionPerformed(evt);
            }
        });
        getContentPane().add(nombre_paciente);
        nombre_paciente.setBounds(430, 70, 150, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Fecha de ingreso:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 110, 110, 14);
        getContentPane().add(fecha_i);
        fecha_i.setBounds(138, 110, 150, 20);

        modificar.setText("Modificar");
        getContentPane().add(modificar);
        modificar.setBounds(140, 330, 75, 23);

        agregar.setText("Agregar");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });
        getContentPane().add(agregar);
        agregar.setBounds(40, 330, 71, 23);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Fecha de salida:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(310, 110, 100, 20);
        getContentPane().add(fecha_salida);
        fecha_salida.setBounds(430, 110, 150, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Nombre del Doctor:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 160, 108, 14);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Valor a pagar");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(180, 230, 80, 14);

        total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalActionPerformed(evt);
            }
        });
        getContentPane().add(total);
        total.setBounds(310, 230, 76, 20);

        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });
        getContentPane().add(buscar);
        buscar.setBounds(230, 330, 65, 23);

        eliminar.setText("Eliminar");
        getContentPane().add(eliminar);
        eliminar.setBounds(320, 330, 69, 23);

        enviar.setText("Mostrar");
        getContentPane().add(enviar);
        enviar.setBounds(410, 330, 69, 23);

        exportar.setText("exportar");
        getContentPane().add(exportar);
        exportar.setBounds(500, 330, 80, 23);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Cedula", "Nombre", "Doctor", "Estado", "Fecha ingreso", "Fecha salida", "Total"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 390, 580, 120);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Estado del paciente:");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(310, 150, 130, 15);

        nombre_doctor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));
        nombre_doctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombre_doctorActionPerformed(evt);
            }
        });
        getContentPane().add(nombre_doctor);
        nombre_doctor.setBounds(140, 150, 150, 20);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Observacion", "Tratamiento", "U.C.I" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(450, 150, 130, 20);

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\SENA\\Documents\\Repositorio\\Tallercontenedores\\src\\iconos\\fondosalida.jpg")); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, 0, 630, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalActionPerformed

    private void nombre_pacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombre_pacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombre_pacienteActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        try {
            // TODO add your handling code here:
            int ced = Integer.parseInt(cedula_paciente.getText().trim());
            
            Conexion con = new Conexion();
            con.ConexionPostgres();
            String query = "SELECT * FROM ingreso WHERE cedula_paciente =" + ced;
            ResultSet rs = con.consultar(query);

            if (rs.next()) {
                nombre_paciente.setText(rs.getString("nombre_paciente"));
                fecha_i.setDate(rs.getDate("fecha_ingreso"));
            } else {
                JOptionPane.showMessageDialog(this, "No existe el Paciente!");
            }

            con.cerrar();
            
            /*
            boolean buscar = false;
            contenedor_ingreso ingreso_s = null;
            //contenedor_ingreso in = null;
            
            for(int i =0; i<ingreso.size(); i++)
            {
            ingreso2 = (contenedor_ingreso)ingreso.get(i);
            
            if(ced==ingreso2.getCedula())
            {
            buscar = true;
            break;
            }
            }
            
            if(buscar)
            {
            nombre_paciente.setText(pac2.getNombre());
            fecha_ingreso.setDate(ingreso2.getFecha_ingreso());
            }else{
            JOptionPane.showMessageDialog(null,"No existen datos!","ERROR",JOptionPane.ERROR_MESSAGE);
            }
            */
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(salida.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(salida.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(salida.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(salida.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buscarActionPerformed

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        try {
            // TODO add your handling code here:
            int ced = Integer.parseInt(cedula_paciente.getText().trim());
            
            formato1 = DateFormat.getDateInstance();
            sfecha = formato1.format(fecha_i.getDate());
            
            Conexion con = new Conexion();
            con.ConexionPostgres();
            String item3 = (String) nombre_doctor.getSelectedItem();
            java.util.StringTokenizer st = new java.util.StringTokenizer(item3, "-");
            String cedula_doc = st.nextToken();
            
            String query = "INSERT INTO salida VALUES("+ced+",'"+nombre_paciente.getText()"','"sfecha"'");
            
            /*
            String nombre_paciente = pac2.getNombre().trim();
            boolean saber = false;
            contenedor_salida salida_a = null;
            
            for(int i =0; i<ingreso.size(); i++)
            {
            ingreso2=(contenedor_ingreso)ingreso.get(i);
            
            if(ced==ingreso2.getCedula());
            {
            saber = true;
            break;
            }
            }
            if(saber)
            {
            fecha_salida.setDate(salida2.getFecha_salida());
            String nombre = (String) nombre_doctor.getSelectedItem();
            //contenedor_salida sali = new contenedor_ingreso();
            //salida.add(sali);
            }else{
            
            }
            //cedula.setText(null);
            //nombre.setText(nombre_paciente);
            //fecha_i.setDate(null);
            */
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(salida.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(salida.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(salida.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(salida.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_agregarActionPerformed

    private void nombre_doctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombre_doctorActionPerformed
        // TODO add your handling code here:
        contenedor_doctor sali2= null;
        String oper=(String)nombre_doctor.getSelectedItem();
       
            nombre_doctor.removeAllItems();
        for(int i=0; i<doctor.doc.size();i++)
        {   sali2=(contenedor_doctor)doc.get(i);
            nombre_doctor.addItem(sali2.getNombre());
            }
       
        
        
    }//GEN-LAST:event_nombre_doctorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(salida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(salida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(salida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(salida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new salida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregar;
    private javax.swing.JButton buscar;
    private javax.swing.JTextField cedula_paciente;
    private javax.swing.JButton eliminar;
    private javax.swing.JButton enviar;
    private javax.swing.JButton exportar;
    private com.toedter.calendar.JDateChooser fecha_i;
    private com.toedter.calendar.JDateChooser fecha_salida;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton modificar;
    private javax.swing.JComboBox<String> nombre_doctor;
    private javax.swing.JTextField nombre_paciente;
    private javax.swing.JTextField total;
    // End of variables declaration//GEN-END:variables
}
